### ISSUE TITLE
OLD issue - needs to be reopened -

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps#47] opened 2023-07-03 12:00 UTC
PLEASE SEE BELOW THE DESCRIPTION OF THE OLD ISSUE AND RESPONSES.

I AM CURRENTLY TEACHING THE COURSE ON GODEPLOY AND NOTICED THE INSTRUCTIONS WERE NOT UPDATED FOR STUDENTS, SO STUDENTS CAN STILL NOT CARRY OUT THIS LAB!

Lab/Demo: 5.1
Task: 1
Step: 10
Description of issue
when completing the work order details, please note you need values for all mandatory fields.
Also the field Taxable is not visible in the form.

Step: 17
Description of issue
default work order type must be set on the incident type before you can convert to a work order.

Step: 19 &20
Description of issue
the inspect system health and inspect range of motion services were not added to the work order -- i suspect the required records were not fully set up for this lab to show the requested result (there are no work order services or tasks in the system).

ephiax20 reacted with thumbs up emoji
@ephiax20
Contributor
ephiax20 commented on Apr 5
Unable to replicate past Step 6, "Incident Type" is not available.

image

@chaast
Author
chaast commented on Apr 5
that's correct. I created a record from scratch for "unit overheating"? but did not know which parameters to set when creating the record -- that's probably why we are getting errors later in the lab.

thank you for confirming Ephiax20.

This potentially requires a pull request maybe?

@CeleneA
Collaborator
CeleneA commented on Apr 11
chaast - did you follow the instructions in the TrainerPrepGuide?
Setup Requirements for Field Service Module

Make Sure that all Users have the Field Service App Access Security Role.
Deploy Field Service Demo Data
a. Locate the FS_Demo_Data.zip file available in the class resources.
b. Right click the FS_Demo_Data.zip file, and choose Unblock (It may not be there and that is OK)
@chaast
Author
[chaast](https://github.com/chaast) commented on Apr 19 • 
Hi Celene, Thank you for your comment. I am grateful you were able to come back to me.

These instructions should be part of the lab set up... or at least part of the set up for the lab provider.... I cannot see anywhere within my lab environment (which is provided by Skillable) an option to access the zip file you mention.

I have read the Training File you refer to, this has a link to a demo video -- but that link does not resolve the lab problems -- the instructions in steps 6, 10, 17, 19 and 20 are not resolved.

This lab needs a revision with correct instructions - or least clarity on how to download the sample data directly into the lab environment when this is provided by Skillable.

thank you for your support.

@CeleneA
Collaborator
[CeleneA](https://github.com/CeleneA) commented [on Apr 19](https://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps/issues/43#issuecomment-1514967551)
Chaast - the lab has been updated and now also includes a link to the demo data.

**Comment by chaast** [comment] 2023-07-03 12:16
It was promised to have these steps added to the lab, but that has not happened... the students need to be able to do this themselves... can you please ensure that the lab will be updated?

Task 1: Add products to the Product Catalog

You are going to create two products. These products will be added to an incident type that students will select when they are creating work orders in the exercise.

Using the navigation on the left, change the Area from Service to Settings.

Under the General group, select Products.

Select the Add Product button.

Configure the Product as follows:

Name: Inspect Health System

Product ID: INS-HEALTH-1234

Unit Group: Default Unit

Default Unit: Primary Unit

Decimals Supported: 2

Select the Field Service tab.

Set the Field Service Product Type field to Service.

Select the Save button to save the record and leave it open.

Select the Publish button and select the Confirm button.

Select the Save and Close button to exit the product.

Select the Add Product button again.

Configure the Product as follows:

Name: Inspect Range of Motion

Product ID: INS-RANGE-1234

Unit Group: Default Unit

Default Unit: Primary Unit

Decimals Supported: 2

Select the Field Service tab.

Set the Field Service Product Type field to Service.

Select the Save button to save the record and leave it open.

Select the Publish button and select the Confirm button.

Select the Save and Close button to exit the product.

Task 2: Create a Price List and add products to it

Now that your products are created, you are going to create a US Bill Rates price list and add the products as price list items.

While still in the Settings area of the application, select Price Lists.

On the Command bar, select the New button.

Set the Price List Name to US Bill Rates.

Select the Save button to save the record and leave it open.

Select the Price List Items tab.

Select the New Price List Item button.

Configure the Price List Item as follows:

Price List: US Bill Rates

Product: Inspect Health System

Unit: Primary Unit

Select the Pricing Information tab.

Leave the Pricing Method at Currency Amount.

Set the Amount field to $150.00.

Select the Save and Close button.

Select the New Price List Item button again.

Configure the Price List Item as follows:

Price List: US Bill Rates

Product: Inspect Range of Motion

Unit: Primary Unit

Select the Pricing Information tab.

Leave the Pricing Method at Currency Amount.

Set the Amount field to $100.00.

Select the Save and Close button.

Task 3: Create Work Order Types

Work order types are used to identify the type of work being done on the work order. We will be associating the Work order type with an Incident type we will be creating in the next task.

Using the navigation on the left, select Work Order Types.

On the Command Bar, select the New button.

In the Name field, enter Service Call.

Set the Price List to US Bill Rates.

Select the Save and Close button.

Task 4: Create a Territory

Using the navigation on the left, select Territories.

On the Command Bar, select the New button.

In the Territory Name field, enter WA.

Select the Save and Close button.

Task 5: Create Incident Types

Incident Types are used to populate information onto work orders when they are created. In this task we will be creating two incident types, Unit Overheating, and Line Connection Lost. We will be populating items to the Unit Overheating Incident type. We will not be adding items to Line Connection Lost incident type, but you are welcome to do so later if you would like.

Using the navigation on the left select Incident Types.

On the Command Bar, select the New button.

In the Name field, enter Unit Overheating.

Select the Details tab.

Set the Default Work Order type to Service Call.

Select the Save button to save the record and leave it open.

Select the Services tab.

Select the New Incident Type Service button.

Configure as follows:

Name: Inspect Health System

Service: Inspect Health System

Unit: Primary Unit

Incident Type: Unit Overheating

Duration: 45 Minutes

Select the Save and Create New button.

Configure as follows:

Name: Inspect Range of Motion

Service: Inspect Range of Motion

Unit: Primary Unit

Incident Type: Unit Overheating

Duration: 1 hour

Select the Save and Close button.

Select the Service Tasks tab.

Select the New Incident Type Service Task button.

Set the Name field to Inspect Unit.

In the Task Type field, select New Service Task Type.

Configure as follows:

Name: Inspect Unit.

Duration: 1 hour

Select the Save and Close button.

Make sure your Incident Type Service Task is as follows:

Name: Inspect Unit

Task Type: Inspect unit

Estimated Duration: 1 Hour

Incident Type: unit Overheating.

Select the Save and Close button.

On the Unit Overheating Incident Type, select the Save and Close button.

Next, we will create the Line Connection Lost Incident Type. If you want to add products, services, and tasks to it later you can.

While on the Active Incident Types screen, select the New button again.

In the Name field, enter Line Connection Lost.

Select the Details tab.

Set the Default Work Order Type to Service Call.

Select the Save and Close button.

You should now have all the supporting elements required

**Comment by ephiax20** [comment] 2023-07-03 13:29
@chaast the Trainer Prep Guide steps are to be completed by the MCT, on environments where it hasn't  been already been done.  The course is not designed for Students to carry out these steps.

**Comment by CeleneA** [comment] 2023-07-03 18:39
Chaast - 
I have added the following note to the lab itself: _
_Note to Instructors: For this lab to work as intended for students, there are a few configuration steps that you will need to complete. You can find the configuration steps in the MB-910T00A Trainer Preparation Guide. You can find the Field Service demo data here_: [https://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps/tree/master/Instructions/Labs]_

I have added the following to the Trainer Prep Guide:
Setup Requirements for Field Service Module

It is important that you walk through the installation of the Field Service demo data.  Without the demo data installed, you will struggle to effectively demonstrate the application.  More importantly, the field service lab will not work for the students.  The demo data includes multiple items that are referenced in the lab.  
•	Manually enter config data: You can manually enter the 6 items that will be needed by students.  The steps for adding the data are located below.  While you won’t have a complete set of working data for demos, you will have the data your students will need to complete the Field Service Lab.  

Manually enter demo data

Task 1: Add products to the Product Catalog
You are going to create two products.  These products will be added to an incident type that students will select when they are creating work orders in the exercise.  
1.	Using the navigation on the left, change the Area from Service to Settings.  
2.	Under the General group, select Products.  
3.	Select the Add Product button.  
4.	Configure the Product as follows:
a.	Name: Inspect Health System
b.	Product ID: INS-HEALTH-1234
c.	Unit Group: Default Unit
d.	Default Unit: Primary Unit
e.	Decimals Supported: 2
5.	Select the Field Service tab. 
6.	Set the Field Service Product Type field to Service.
7.	Select the Save button to save the record and leave it open.  
8.	Select the Publish button and select the Confirm button.  
9.	Select the Save and Close button to exit the product.  
10.	Select the Add Product button again.  
11.	Configure the Product as follows:
a.	Name: Inspect Range of Motion
b.	Product ID: INS-RANGE-1234
c.	Unit Group: Default Unit
d.	Default Unit: Primary Unit
e.	Decimals Supported: 2
12.	Select the Field Service tab. 
13.	Set the Field Service Product Type field to Service.
14.	Select the Save button to save the record and leave it open.  
15.	Select the Publish button and select the Confirm button.  
16.	Select the Save and Close button to exit the product.  

Task 2: Create a Price List and add products to it
Now that your products are created, you are going to create a US Bill Rates price list and add the products as price list items.    

1.	While still in the Settings area of the application, select Price Lists. 
2.	On the Command bar, select the New button.  
3.	Set the Price List Name to US Bill Rates.
4.	Select the Save button to save the record and leave it open.  
5.	Select the Price List Items tab.  
6.	Select the New Price List Item button.  
7.	Configure the Price List Item as follows:
a.	Price List: US Bill Rates
b.	Product: Inspect Health System
c.	Unit: Primary Unit
8.	Select the Pricing Information tab.  
9.	Leave the Pricing Method at Currency Amount.
10.	Set the Amount field to $150.00.
11.	Select the Save and Close button.
12.	Select the New Price List Item button again.  
13.	Configure the Price List Item as follows:
a.	Price List: US Bill Rates
b.	Product: Inspect Range of Motion
c.	Unit: Primary Unit
14.	Select the Pricing Information tab.  
15.	Leave the Pricing Method at Currency Amount.
16.	Set the Amount field to $100.00.
17.	Select the Save and Close button.

Task 3: Create Work Order Types
Work order types are used to identify the type of work being done on the work order.  We will be associating the Work order type with an Incident type we will be creating in the next task.  
1.	Using the navigation on the left, select Work Order Types.  
2.	On the Command Bar, select the New button.  
3.	In the Name field, enter Service Call.  
4.	Set the Price List to US Bill Rates. 
5.	Select the Save and Close button. 

Task 4: Create a Territory
1.	Using the navigation on the left, select Territories.  
2.	On the Command Bar, select the New button.  
3.	In the Territory Name field, enter WA.  
4.	Select the Save and Close button. 


Task 5: Create Incident Types
Incident Types are used to populate information onto work orders when they are created.  In this task we will be creating two incident types, Unit Overheating, and Line Connection Lost.  We will be populating items to the Unit Overheating Incident type.  We will not be adding items to Line Connection Lost incident type, but you are welcome to do so later if you would like. 
1.	Using the navigation on the left select Incident Types.  
2.	On the Command Bar, select the New button. 
3.	In the Name field, enter Unit Overheating.
4.	Select the Details tab.  
5.	Set the Default Work Order type to Service Call.  
6.	Select the Save button to save the record and leave it open.  
7.	Select the Services tab.  
8.	Select the New Incident Type Service button.  
9.	Configure as follows:
a.	Name: Inspect Health System
b.	Service: Inspect Health System
c.	Unit: Primary Unit
d.	Incident Type: Unit Overheating
e.	Duration: 45 Minutes
10.	Select the Save and Create New button. 
11.	Configure as follows:
a.	Name: Inspect Range of Motion
b.	Service: Inspect Range of Motion
c.	Unit: Primary Unit
d.	Incident Type: Unit Overheating
e.	Duration: 1 hour
12.	Select the Save and Close button. 
13.	Select the Service Tasks tab.  
14.	Select the New Incident Type Service Task button.  
15.	Set the Name field to Inspect Unit. 
16.	In the Task Type field, select New Service Task Type.
17.	Configure as follows:
a.	Name: Inspect Unit.
b.	Duration: 1 hour
18.	Select the Save and Close button.  
19.	Make sure your Incident Type Service Task is as follows:
a.	Name: Inspect Unit
b.	Task Type: Inspect unit
c.	Estimated Duration: 1 Hour
d.	Incident Type: unit Overheating.  
20.	Select the Save and Close button.  
21.	On the Unit Overheating Incident Type, select the Save and Close button.
Next, we will create the Line Connection Lost Incident Type.  If you want to add products, services, and tasks to it later you can.  
22.	While on the Active Incident Types screen, select the New button again. 
23.	In the Name field, enter Line Connection Lost.
24.	Select the Details tab.
25.	Set the Default Work Order Type to Service Call.  
26.	Select the Save and Close button.  
You should now have all the supporting elements required for your students to leverage in class.  

I just want to confirm that you went through the steps to create the relevant demo data. As ephiax20 mentioned, the steps to add demo data are not intended to be completed by students. Therefore the instructions are in the Trainer Prep Guide. I did (as shown above) add a note for the trainer that the steps are in the Trainer Prep Guide.

Please let me know how I can make this process more clear.
Thank you,
Celene

**Comment by chaast** [comment] 2023-07-03 19:57
Hi Celene, I still think that these instructions should be made available to students - as an instructor I don’t always have time to set up the lab in advance if the day of teaching!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CeleneA** [comment] 2023-07-06 19:25
Chaast, 
I understand your concern. But there isn't really time in the course schedule to allow for that. I am thinking the better option would be to replace the lab with a click-through demo.
That would remove the need for instructors to do the setup, and learners would still get an experience of the process.
I am going to close this issue, but please reach out to me at celene.abramson@microsoft.com and let me know your thoughts.

**Closed by CeleneA** 2023-07-06 19:25 UTC
